name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-appimage:

    runs-on: ubuntu-latest
    container:
      image: appimagecrafters/appimage-builder

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: apt-get install -y qt5-default qtdeclarative5-dev cmake
    - name: build-appimage
      run: appimage-builder --skip-test
    - uses: actions/upload-artifact@v2
      with:
        path: *.AppImage*